default: &default
  url: redis://localhost:6379
  sidekiq:
    namespace: anemone-<%= Rails.env %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  url: <%= ENV['REDIS_URL'] %>
